server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root


mybatis:
  # 在resource文件夹下会有一个文件夹叫mapper，这个文件夹下用来放所有的Mybatis的xml文件
  mapper-locations: classpath:mapper/*.xml
  # 在具体的mapper文件中 有一个paramtype属性会指向参数类型
  # 如果参数类型是一个实体类，那么就会从一下的目录下去寻找实体类
  type-aliases-package: com.atguigu.springcloud.entities
eureka:
  client:
    # 表示是否将自己注册进 eurekaServer默认为true
    register-with-eureka: true
    # 是否从eurekaServer抓取已有的注册信息，默认为true，单节点无所谓，急缺必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    # 对主机名的修改
    instance-id: payment8001
    # 访问服务路径时可以显示这个服务所部署的ip地址
    prefer-ip-address: true
#    # eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认为30秒）
#    lease-renewal-interval-in-seconds: 1
#    # eureka服务端在收到最后一个次心跳后等待的上限，单位为秒（默认为90秒），超时将被踢出
#    lease-expiration-duration-in-seconds: 2