server:
  port: 2001

spring:
  appliaction:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要 seata-service 中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: locahost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

feign:
  hystrix:
    enabled: true

logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/*.xml